package data_transfer_object

type ReadingResponse struct {
	Language string   `json:"language"`
	Function []string `json:"function"`
	HasError bool     `json:"hasError"`
	Msg      string   `json:"msg"`
	Code     string   `json:"code"`
	Data     struct {
		Info struct {
			PowerstationId      string      `json:"powerstation_id"`
			Time                string      `json:"time"`
			DateFormat          string      `json:"date_format"`
			DateFormatYm        string      `json:"date_format_ym"`
			Stationname         string      `json:"stationname"`
			Address             string      `json:"address"`
			OwnerName           interface{} `json:"owner_name"`
			OwnerPhone          interface{} `json:"owner_phone"`
			OwnerEmail          string      `json:"owner_email"`
			BatteryCapacity     float64     `json:"battery_capacity"`
			TurnonTime          string      `json:"turnon_time"`
			CreateTime          string      `json:"create_time"`
			Capacity            float64     `json:"capacity"`
			Longitude           float64     `json:"longitude"`
			Latitude            float64     `json:"latitude"`
			PowerstationType    string      `json:"powerstation_type"`
			Status              int         `json:"status"`
			IsStored            bool        `json:"is_stored"`
			IsPowerflow         bool        `json:"is_powerflow"`
			ChartsType          int         `json:"charts_type"`
			HasPv               bool        `json:"has_pv"`
			HasStatisticsCharts bool        `json:"has_statistics_charts"`
			OnlyBps             bool        `json:"only_bps"`
			OnlyBpu             bool        `json:"only_bpu"`
			TimeSpan            float64     `json:"time_span"`
			PrValue             string      `json:"pr_value"`
		} `json:"info"`
		Kpi struct {
			MonthGeneration float64 `json:"month_generation"`
			Pac             float64 `json:"pac"`
			Power           float64 `json:"power"`
			TotalPower      float64 `json:"total_power"`
			DayIncome       float64 `json:"day_income"`
			TotalIncome     float64 `json:"total_income"`
			YieldRate       float64 `json:"yield_rate"`
			Currency        string  `json:"currency"`
		} `json:"kpi"`
		PowercontrolStatus int           `json:"powercontrol_status"`
		Images             []interface{} `json:"images"`
		Weather            struct {
			HeWeather6 []struct {
				DailyForecast []struct {
					CondCodeD string `json:"cond_code_d"`
					CondCodeN string `json:"cond_code_n"`
					CondTxtD  string `json:"cond_txt_d"`
					CondTxtN  string `json:"cond_txt_n"`
					Date      string `json:"date"`
					Time      string `json:"time"`
					Hum       string `json:"hum"`
					Pcpn      string `json:"pcpn"`
					Pop       string `json:"pop"`
					Pres      string `json:"pres"`
					TmpMax    string `json:"tmp_max"`
					TmpMin    string `json:"tmp_min"`
					UvIndex   string `json:"uv_index"`
					Vis       string `json:"vis"`
					WindDeg   string `json:"wind_deg"`
					WindDir   string `json:"wind_dir"`
					WindSc    string `json:"wind_sc"`
					WindSpd   string `json:"wind_spd"`
				} `json:"daily_forecast"`
				Basic struct {
					Cid      string `json:"cid"`
					Location string `json:"location"`
					Cnty     string `json:"cnty"`
					Lat      string `json:"lat"`
					Lon      string `json:"lon"`
					Tz       string `json:"tz"`
				} `json:"basic"`
				Update struct {
					Loc string `json:"loc"`
					Utc string `json:"utc"`
				} `json:"update"`
				Status string `json:"status"`
			} `json:"HeWeather6"`
		} `json:"weather"`
		Inverter []struct {
			Sn   string `json:"sn"`
			Dict struct {
				Left []struct {
					IsHT         bool   `json:"isHT"`
					Key          string `json:"key"`
					Value        string `json:"value"`
					Unit         string `json:"unit"`
					IsFaultMsg   int    `json:"isFaultMsg"`
					FaultMsgCode int    `json:"faultMsgCode"`
				} `json:"left"`
				Right []struct {
					IsHT         bool   `json:"isHT"`
					Key          string `json:"key"`
					Value        string `json:"value"`
					Unit         string `json:"unit"`
					IsFaultMsg   int    `json:"isFaultMsg"`
					FaultMsgCode int    `json:"faultMsgCode"`
				} `json:"right"`
			} `json:"dict"`
			IsStored    bool    `json:"is_stored"`
			Name        string  `json:"name"`
			InPac       float64 `json:"in_pac"`
			OutPac      float64 `json:"out_pac"`
			Eday        float64 `json:"eday"`
			Emonth      float64 `json:"emonth"`
			Etotal      float64 `json:"etotal"`
			Status      int     `json:"status"`
			TurnonTime  string  `json:"turnon_time"`
			ReleationId string  `json:"releation_id"`
			Type        string  `json:"type"`
			Capacity    float64 `json:"capacity"`
			D           struct {
				PwId                  string  `json:"pw_id"`
				Capacity              string  `json:"capacity"`
				Model                 string  `json:"model"`
				OutputPower           string  `json:"output_power"`
				OutputCurrent         string  `json:"output_current"`
				GridVoltage           string  `json:"grid_voltage"`
				BackupOutput          string  `json:"backup_output"`
				Soc                   string  `json:"soc"`
				Soh                   string  `json:"soh"`
				LastRefreshTime       string  `json:"last_refresh_time"`
				WorkMode              string  `json:"work_mode"`
				DcInput1              string  `json:"dc_input1"`
				DcInput2              string  `json:"dc_input2"`
				Battery               string  `json:"battery"`
				BmsStatus             string  `json:"bms_status"`
				Warning               string  `json:"warning"`
				ChargeCurrentLimit    string  `json:"charge_current_limit"`
				DischargeCurrentLimit string  `json:"discharge_current_limit"`
				FirmwareVersion       float64 `json:"firmware_version"`
				CreationDate          string  `json:"creationDate"`
				EDay                  float64 `json:"eDay"`
				ETotal                float64 `json:"eTotal"`
				Pac                   float64 `json:"pac"`
				HTotal                float64 `json:"hTotal"`
				Vpv1                  float64 `json:"vpv1"`
				Vpv2                  float64 `json:"vpv2"`
				Vpv3                  float64 `json:"vpv3"`
				Vpv4                  float64 `json:"vpv4"`
				Ipv1                  float64 `json:"ipv1"`
				Ipv2                  float64 `json:"ipv2"`
				Ipv3                  float64 `json:"ipv3"`
				Ipv4                  float64 `json:"ipv4"`
				Vac1                  float64 `json:"vac1"`
				Vac2                  float64 `json:"vac2"`
				Vac3                  float64 `json:"vac3"`
				Iac1                  float64 `json:"iac1"`
				Iac2                  float64 `json:"iac2"`
				Iac3                  float64 `json:"iac3"`
				Fac1                  float64 `json:"fac1"`
				Fac2                  float64 `json:"fac2"`
				Fac3                  float64 `json:"fac3"`
				Istr1                 float64 `json:"istr1"`
				Istr2                 float64 `json:"istr2"`
				Istr3                 float64 `json:"istr3"`
				Istr4                 float64 `json:"istr4"`
				Istr5                 float64 `json:"istr5"`
				Istr6                 float64 `json:"istr6"`
				Istr7                 float64 `json:"istr7"`
				Istr8                 float64 `json:"istr8"`
				Istr9                 float64 `json:"istr9"`
				Istr10                float64 `json:"istr10"`
				Istr11                float64 `json:"istr11"`
				Istr12                float64 `json:"istr12"`
				Istr13                float64 `json:"istr13"`
				Istr14                float64 `json:"istr14"`
				Istr15                float64 `json:"istr15"`
				Istr16                float64 `json:"istr16"`
			} `json:"d"`
			ItChangeFlag bool        `json:"it_change_flag"`
			Tempperature float64     `json:"tempperature"`
			CheckCode    string      `json:"check_code"`
			Next         interface{} `json:"next"`
			Prev         interface{} `json:"prev"`
			NextDevice   struct {
				Sn       interface{} `json:"sn"`
				IsStored bool        `json:"isStored"`
			} `json:"next_device"`
			PrevDevice struct {
				Sn       interface{} `json:"sn"`
				IsStored bool        `json:"isStored"`
			} `json:"prev_device"`
			InvertFull struct {
				Sn                      string      `json:"sn"`
				PowerstationId          string      `json:"powerstation_id"`
				Name                    string      `json:"name"`
				ModelType               string      `json:"model_type"`
				ChangeType              int         `json:"change_type"`
				ChangeTime              int         `json:"change_time"`
				Capacity                float64     `json:"capacity"`
				Eday                    float64     `json:"eday"`
				Iday                    float64     `json:"iday"`
				Etotal                  float64     `json:"etotal"`
				Itotal                  float64     `json:"itotal"`
				HourTotal               float64     `json:"hour_total"`
				Status                  int         `json:"status"`
				TurnonTime              int64       `json:"turnon_time"`
				Pac                     float64     `json:"pac"`
				Tempperature            float64     `json:"tempperature"`
				Vpv1                    float64     `json:"vpv1"`
				Vpv2                    float64     `json:"vpv2"`
				Vpv3                    float64     `json:"vpv3"`
				Vpv4                    float64     `json:"vpv4"`
				Ipv1                    float64     `json:"ipv1"`
				Ipv2                    float64     `json:"ipv2"`
				Ipv3                    float64     `json:"ipv3"`
				Ipv4                    float64     `json:"ipv4"`
				Vac1                    float64     `json:"vac1"`
				Vac2                    float64     `json:"vac2"`
				Vac3                    float64     `json:"vac3"`
				Iac1                    float64     `json:"iac1"`
				Iac2                    float64     `json:"iac2"`
				Iac3                    float64     `json:"iac3"`
				Fac1                    float64     `json:"fac1"`
				Fac2                    float64     `json:"fac2"`
				Fac3                    float64     `json:"fac3"`
				Istr1                   float64     `json:"istr1"`
				Istr2                   float64     `json:"istr2"`
				Istr3                   float64     `json:"istr3"`
				Istr4                   float64     `json:"istr4"`
				Istr5                   float64     `json:"istr5"`
				Istr6                   float64     `json:"istr6"`
				Istr7                   float64     `json:"istr7"`
				Istr8                   float64     `json:"istr8"`
				Istr9                   float64     `json:"istr9"`
				Istr10                  float64     `json:"istr10"`
				Istr11                  float64     `json:"istr11"`
				Istr12                  float64     `json:"istr12"`
				Istr13                  float64     `json:"istr13"`
				Istr14                  float64     `json:"istr14"`
				Istr15                  float64     `json:"istr15"`
				Istr16                  float64     `json:"istr16"`
				LastTime                int64       `json:"last_time"`
				Vbattery1               float64     `json:"vbattery1"`
				Ibattery1               float64     `json:"ibattery1"`
				Pmeter                  float64     `json:"pmeter"`
				Soc                     float64     `json:"soc"`
				Soh                     float64     `json:"soh"`
				BmsDischargeIMax        interface{} `json:"bms_discharge_i_max"`
				BmsChargeIMax           float64     `json:"bms_charge_i_max"`
				BmsWarning              int         `json:"bms_warning"`
				BmsAlarm                int         `json:"bms_alarm"`
				BattaryWorkMode         int         `json:"battary_work_mode"`
				Workmode                int         `json:"workmode"`
				Vload                   float64     `json:"vload"`
				Iload                   float64     `json:"iload"`
				Firmwareversion         float64     `json:"firmwareversion"`
				Pbackup                 float64     `json:"pbackup"`
				Seller                  float64     `json:"seller"`
				Buy                     float64     `json:"buy"`
				Yesterdaybuytotal       interface{} `json:"yesterdaybuytotal"`
				Yesterdaysellertotal    interface{} `json:"yesterdaysellertotal"`
				Yesterdayct2Sellertotal interface{} `json:"yesterdayct2sellertotal"`
				Yesterdayetotal         interface{} `json:"yesterdayetotal"`
				Yesterdayetotalload     interface{} `json:"yesterdayetotalload"`
				Yesterdaylastime        int         `json:"yesterdaylastime"`
				Thismonthetotle         float64     `json:"thismonthetotle"`
				Lastmonthetotle         float64     `json:"lastmonthetotle"`
				Ram                     float64     `json:"ram"`
				Outputpower             float64     `json:"outputpower"`
				FaultMessge             int         `json:"fault_messge"`
				Isbuettey               bool        `json:"isbuettey"`
				Isbuetteybps            bool        `json:"isbuetteybps"`
				Isbuetteybpu            bool        `json:"isbuetteybpu"`
				IsESUOREMU              bool        `json:"isESUOREMU"`
				BackUpPloadS            float64     `json:"backUpPload_S"`
				BackUpVloadS            float64     `json:"backUpVload_S"`
				BackUpIloadS            float64     `json:"backUpIload_S"`
				BackUpPloadT            float64     `json:"backUpPload_T"`
				BackUpVloadT            float64     `json:"backUpVload_T"`
				BackUpIloadT            float64     `json:"backUpIload_T"`
				ETotalBuy               interface{} `json:"eTotalBuy"`
				EDayBuy                 float64     `json:"eDayBuy"`
				EBatteryCharge          interface{} `json:"eBatteryCharge"`
				EChargeDay              float64     `json:"eChargeDay"`
				EBatteryDischarge       interface{} `json:"eBatteryDischarge"`
				EDischargeDay           float64     `json:"eDischargeDay"`
				BattStrings             float64     `json:"battStrings"`
				MeterConnectStatus      interface{} `json:"meterConnectStatus"`
				MtActivepowerR          float64     `json:"mtActivepowerR"`
				MtActivepowerS          float64     `json:"mtActivepowerS"`
				MtActivepowerT          float64     `json:"mtActivepowerT"`
				EzProConnectStatus      interface{} `json:"ezPro_connect_status"`
				Dataloggersn            string      `json:"dataloggersn"`
				EquipmentName           interface{} `json:"equipment_name"`
				Hasmeter                bool        `json:"hasmeter"`
				MeterType               interface{} `json:"meter_type"`
				PreHourLasttotal        float64     `json:"pre_hour_lasttotal"`
				PreHourTime             int64       `json:"pre_hour_time"`
				CurrentHourPv           float64     `json:"current_hour_pv"`
				ExtendProperties        interface{} `json:"extend_properties"`
				EPConnectStatusHappen   interface{} `json:"eP_connect_status_happen"`
				EPConnectStatusRecover  interface{} `json:"eP_connect_status_recover"`
				TotalSell               float64     `json:"total_sell"`
				TotalBuy                float64     `json:"total_buy"`
				Errors                  interface{} `json:"errors"`
				SafetyConutry           float64     `json:"safetyConutry"`
			} `json:"invert_full"`
			Time                     string  `json:"time"`
			Battery                  string  `json:"battery"`
			FirmwareVersion          float64 `json:"firmware_version"`
			WarningBms               string  `json:"warning_bms"`
			Soh                      string  `json:"soh"`
			DischargeCurrentLimitBms string  `json:"discharge_current_limit_bms"`
			ChargeCurrentLimitBms    string  `json:"charge_current_limit_bms"`
			Soc                      string  `json:"soc"`
			PvInput2                 string  `json:"pv_input_2"`
			PvInput1                 string  `json:"pv_input_1"`
			BackUpOutput             string  `json:"back_up_output"`
			OutputVoltage            string  `json:"output_voltage"`
			BackupVoltage            string  `json:"backup_voltage"`
			OutputCurrent            string  `json:"output_current"`
			OutputPower              string  `json:"output_power"`
			TotalGeneration          string  `json:"total_generation"`
			DailyGeneration          string  `json:"daily_generation"`
			BatteryCharging          string  `json:"battery_charging"`
			LastRefreshTime          string  `json:"last_refresh_time"`
			BmsStatus                string  `json:"bms_status"`
			PwId                     string  `json:"pw_id"`
			FaultMessage             string  `json:"fault_message"`
			BatteryPower             float64 `json:"battery_power"`
			PointIndex               string  `json:"point_index"`
			Points                   []struct {
				TargetIndex   int         `json:"target_index"`
				TargetName    string      `json:"target_name"`
				Display       string      `json:"display"`
				Unit          string      `json:"unit"`
				TargetKey     string      `json:"target_key"`
				TextCn        string      `json:"text_cn"`
				TargetSnSix   interface{} `json:"target_sn_six"`
				TargetSnSeven interface{} `json:"target_sn_seven"`
				TargetType    interface{} `json:"target_type"`
				StorageName   interface{} `json:"storage_name"`
			} `json:"points"`
			BackupPloadS       float64     `json:"backup_pload_s"`
			BackupVloadS       float64     `json:"backup_vload_s"`
			BackupIloadS       float64     `json:"backup_iload_s"`
			BackupPloadT       float64     `json:"backup_pload_t"`
			BackupVloadT       float64     `json:"backup_vload_t"`
			BackupIloadT       float64     `json:"backup_iload_t"`
			EtotalBuy          interface{} `json:"etotal_buy"`
			EdayBuy            float64     `json:"eday_buy"`
			EbatteryCharge     interface{} `json:"ebattery_charge"`
			EchargeDay         float64     `json:"echarge_day"`
			EbatteryDischarge  interface{} `json:"ebattery_discharge"`
			EdischargeDay      float64     `json:"edischarge_day"`
			BattStrings        float64     `json:"batt_strings"`
			MeterConnectStatus interface{} `json:"meter_connect_status"`
			MtactivepowerR     float64     `json:"mtactivepower_r"`
			MtactivepowerS     float64     `json:"mtactivepower_s"`
			MtactivepowerT     float64     `json:"mtactivepower_t"`
			HasTigo            bool        `json:"has_tigo"`
			CanStartIV         bool        `json:"canStartIV"`
		} `json:"inverter"`
		Hjgx struct {
			Co2  float64 `json:"co2"`
			Tree float64 `json:"tree"`
			Coal float64 `json:"coal"`
		} `json:"hjgx"`
		PrePowerstationId interface{} `json:"pre_powerstation_id"`
		NexPowerstationId interface{} `json:"nex_powerstation_id"`
		HomKit            struct {
			HomeKitLimit bool   `json:"homeKitLimit"`
			Sn           string `json:"sn"`
		} `json:"homKit"`
		IsTigo                 bool `json:"isTigo"`
		TigoIntervalTimeMinute int  `json:"tigoIntervalTimeMinute"`
		SmuggleInfo            struct {
			IsAllSmuggle    bool        `json:"isAllSmuggle"`
			IsSmuggle       bool        `json:"isSmuggle"`
			DescriptionText interface{} `json:"descriptionText"`
			Sns             interface{} `json:"sns"`
		} `json:"smuggleInfo"`
		Powerflow struct {
			Pv                        string      `json:"pv"`
			PvStatus                  int         `json:"pvStatus"`
			Bettery                   string      `json:"bettery"`
			BetteryStatus             int         `json:"betteryStatus"`
			BetteryStatusStr          interface{} `json:"betteryStatusStr"`
			Load                      string      `json:"load"`
			LoadStatus                int         `json:"loadStatus"`
			Grid                      string      `json:"grid"`
			Soc                       int         `json:"soc"`
			SocText                   string      `json:"socText"`
			HasEquipment              bool        `json:"hasEquipment"`
			GridStatus                int         `json:"gridStatus"`
			IsHomKit                  bool        `json:"isHomKit"`
			IsBpuAndInverterNoBattery bool        `json:"isBpuAndInverterNoBattery"`
			IsMoreBettery             bool        `json:"isMoreBettery"`
		} `json:"powerflow"`
		EnergeStatisticsCharts struct {
			Sum               float64 `json:"sum"`
			Buy               float64 `json:"buy"`
			BuyPercent        float64 `json:"buyPercent"`
			Sell              float64 `json:"sell"`
			SellPercent       float64 `json:"sellPercent"`
			SelfUseOfPv       float64 `json:"selfUseOfPv"`
			ConsumptionOfLoad float64 `json:"consumptionOfLoad"`
			ChartsType        int     `json:"chartsType"`
			HasPv             bool    `json:"hasPv"`
			HasCharge         bool    `json:"hasCharge"`
			Charge            float64 `json:"charge"`
			DisCharge         float64 `json:"disCharge"`
		} `json:"energeStatisticsCharts"`
		Soc struct {
			Power  int `json:"power"`
			Status int `json:"status"`
		} `json:"soc"`
	} `json:"data"`
	Components struct {
		Para         string      `json:"para"`
		LangVer      int         `json:"langVer"`
		TimeSpan     int         `json:"timeSpan"`
		Api          string      `json:"api"`
		MsgSocketAdr interface{} `json:"msgSocketAdr"`
	} `json:"components"`
}
